[tool.black]
line-length = 120

[tool.pylint.'MESSAGES CONTROL']
disable = "invalid-name,too-many-instance-attributes,too-many-locals,missing-function-docstring,too-many-arguments"

[tool.pylint.MAIN]
max-line-length = 120

[tool.mypy]
mypy_path = "stubs"

plugins = [
    "numpy.typing.mypy_plugin",
    "pydantic.mypy",
]
