---
inputs:
  sottozone_allerta_er:
    type: shape
    path: shapes/Sottozone_allerta_ER
  punti_citta:
    type: static
    path: puntiCitta.geo
flavours:
 - name: default
   steps:
     add_basemap:
       params:
         # Italia
         # For an example of more, see skinnywms/plot/magics.py
         page_id_line: off
         output_width: 1280
         subpage_map_projection: cylindrical
         subpage_lower_left_longitude: 2.5
         subpage_lower_left_latitude: 35.0
         subpage_upper_right_longitude: 20.0
         subpage_upper_right_latitude: 50.0
         page_x_length: 38
         page_y_length: 31
         super_page_x_length: 40
         super_page_y_length: 32
         subpage_x_length: 34
         subpage_y_length: 30
         subpage_x_position: 2
         subpage_y_position: 1
         map_grid: on
         map_grid_latitude_reference: 45.0
         map_grid_longitude_reference: 0.0
         map_grid_longitude_increment: 2.5
         map_grid_latitude_increment: 2.5
         map_grid_colour: grey
         map_grid_line_style: dash
         map_label_colour: black
         map_label_height: 0.4
         map_label_latitude_frequency : 1
     add_boundaries:
       params:
         map_boundaries: on
         map_boundaries_colour: "#504040"
         map_administrative_boundaries_countries_list: ["ITA"]
         map_administrative_boundaries_colour: "#504040"
         map_administrative_boundaries_style: solid
         map_administrative_boundaries: on
     add_user_boundaries:
       skip: yes
     add_geopoints:
       skip: yes
     add_symbols:
       skip: yes
 - name: emro
   steps:
     add_basemap:
       params:
         # Emilia-Romagna
         page_id_line: off
         output_width: 1000
         subpage_map_projection: polar_stereographic
         subpage_lower_left_longitude: 9.0
         subpage_lower_left_latitude: 43.4
         subpage_upper_right_longitude: 13.2
         subpage_upper_right_latitude: 45.2
         subpage_map_vertical_longitude: 11.0
         map_grid: on
         map_grid_latitude_reference: 45.0
         map_grid_longitude_reference: 0.0
         map_grid_longitude_increment: 1.0
         map_grid_latitude_increment: 1.0
         map_grid_colour: grey
         map_grid_line_style: dash
         map_label_colour: black
         map_label_height: 0.4
         map_label_latitude_frequency : 1
     add_user_boundaries:
       shape: sottozone_allerta_er
       params:
         map_user_layer_colour: blue
         map_coastline_resolution: high
     add_geopoints:
       points: punti_citta
 - name: nord
   steps:
     add_basemap:
       params:
         # Nord Italia
         page_id_line: off
         output_width: 1000
         subpage_map_projection: mercator
         subpage_lower_left_longitude: 5.1
         subpage_lower_left_latitude: 43.0
         subpage_upper_right_longitude: 15.0
         subpage_upper_right_latitude: 47.5
         subpage_map_vertical_longitude: 10.3
         page_x_length: 38
         page_y_length: 24
         super_page_x_length: 40
         super_page_y_length: 25
         subpage_x_length: 34
         subpage_y_length: 23
         subpage_x_position: 2
         subpage_y_position: 1
         map_grid: on
         map_grid_latitude_reference: 45.0
         map_grid_longitude_reference: 0.0
         map_grid_longitude_increment: 1.0
         map_grid_latitude_increment: 1.0
         map_grid_colour: grey
         map_grid_line_style: dash
         map_label_colour: black
         map_label_height: 0.4
         map_label_latitude_frequency : 1
     add_boundaries:
       params:
         map_coastline_resolution: high
         map_boundaries: on
         map_boundaries_colour: "#504040"
         map_administrative_boundaries_countries_list: ["ITA"]
         map_administrative_boundaries_colour: "#504040"
         map_administrative_boundaries_style: solid
         map_administrative_boundaries: on
     add_user_boundaries:
       shape: sottozone_allerta_er
       params:
         map_user_layer_colour: blue
         map_coastline_resolution: high
     add_geopoints:
       points: punti_citta
