from typing import BinaryIO

from numpy.typing import NDArray

def codes_grib_new_from_file(fileobj: BinaryIO, headers_only: bool = False) -> int: ...
def codes_get_long(msgid: int, key: str) -> int: ...
def codes_get_string(msgid: int, key: str) -> str: ...
def codes_get_double(msgid: int, key: str) -> float: ...
def codes_get_values(msgid: int) -> NDArray: ...
def codes_set_long(msgid: int, key: str, value: int) -> None: ...
def codes_set_string(msgid: int, key: str, value: str) -> None: ...
def codes_set_double(msgid: int, key: str, value: float) -> None: ...
def codes_set_values(msgid: int, values: NDArray) -> None: ...
def codes_get_message(msgid: int) -> bytes: ...

class KeyValueNotFoundError(Exception): ...
