from typing import Any

class macro:
    @staticmethod
    def output(**kwargs) -> Any: ...
    @staticmethod
    def mmap(**kwargs) -> Any: ...
    @staticmethod
    def msymb(**kwargs) -> Any: ...
    @staticmethod
    def plot(*args) -> None: ...

class Magics:
    class MagicsError(Exception): ...
